REPO_TAGLINE: Numerical methods • approximation • stability & error
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: coding
SITE_URL: https://academic-codex.github.io/SME0600-Calculo-Numerico

BG_1: "#0B1220"
BG_2: "#0F2A3D"
TEXT_MAIN: "#EAF6FF"
TEXT_MUTED: "#B7D6EA"
ACCENT: "#22D3EE"
CARD_RADIUS: "18"